# Generated by Django 5.2.8 on 2026-04-22 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=20)),
                ('dept_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_age', models.IntegerField()),
                ('emp_start_date', models.DateField()),
                ('emp_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.department')),
            ],
        ),
    ]
